### ISSUE TITLE
[Technical Support For Listing] Bitrue Exchange Ticket (58988) 

### ISSUE THREAD

**Issue by BitrueExchange** [input-output-hk/cardano-byron-cli#110] opened 2019-03-25 11:07 UTC
We have two quick questions regarding the implementation, can you please help us take a look?

1. When creating wallet via cardano-cli, how do you set mnemonic words? And if will the wallet be able to be recovered from another device which has cardano-cli installed? 

2. What is the maximum number of addresses allowed in each wallet under the cardano-cli?

3. We did a test in which we have sent a certain amount of ADAs to two different addresses in one wallet under the cardano-cli, but only to see UTXO shown in one of the addresses after executing cardano-cli wallet utxos.

Thanks for your help!

---------

Following is the original ticket sent to iohk

Here's the list of questions:

Can the address be generated offline? Can we pull out the private key once generated offline? 

Will the transaction be generated offline and broadcasted through the node after being signed with the private key?

Do you support JSON-RPC type of request like Ethereum does?

If we use cardano-cli as a black-box program to support ADA, how do we ensure that the value of “actual fee” is larger than that of “fee”? Because the fee and tx-bytes will only show after input and output being filled.

Can the private key of the address be exported using cardano-cli?

Can we pull out the original transaction hash that has been signed (before being broadcasted) using cardano-cli?

Can the cardano-cli be used as a node, for the purpose of like searching for transactions and checking balances. Do you have an API for it?

How do other exchanges support ADA, is it via cardano-cli or cardano-sl?

How do other exchanges confirm transactions? Is it by using lowest assurance, medium assurance or high assurance?

Can the private key be exported from cardano-sl’s wallet address?

Can we pull out the original transaction hash that has been signed (before being broadcasted) using cardano-sl?

While using the API from cardano-api package, what does “cbeBlockLead” and “cbsMerkleRoot” mean in the block details section?

While using the API from cardano-api package, what does “ctsRelayedBy” mean in the transaction details section?

How long does it normally take to produce a block? Is it around 20 seconds? The 20 seconds result is a calculation based on the comparison between different values of   “ctbTimeIssued” from cardano-api since it’s not shown in the explorer.

**Comment by BitrueExchange** [comment] 2019-03-26 08:09
+Adding one more most URGENT question:

When creating wallet via cardano-cli, how do you set mnemonic words? And if will the wallet be able to be recovered from another device which has cardano-cli installed?

**Comment by NicolasDP** [comment] 2019-03-26 09:34
> 1. When creating wallet via cardano-cli, how do you set mnemonic words? And if will the wallet be able to be recovered from another device which has cardano-cli installed?

You can set the mnemonic words utilising the `recover` command. Or you can create/generate a new one. Mnemonics can be recovered from any devices with cardano-cli.

> What is the maximum number of addresses allowed in each wallet under the cardano-cli?

It depends. If you are utilising the bip44 wallet option, I'd suggest that you make sure you have at least one address on the blockchain every 10 address generated.

> We did a test in which we have sent a certain amount of ADAs to two different addresses in one wallet under the cardano-cli, but only to see UTXO shown in one of the addresses after executing cardano-cli wallet utxos.

`cardano-cli wallet utxos` shows the Unspent Transaction Output. If you want to see all your transaction history, have a look at `cardano-cli wallet statement`

> Can the address be generated offline? Can we pull out the private key once generated offline?

You can generate the address offline, unfortunately we do not support providing the private key out of the wallet yet. This could be an additional feature that could be added.

> Will the transaction be generated offline and broadcasted through the node after being signed with the private key?

The transactions are built offline. You can even pass the built and signed transaction from a secured offline computer and then broadcast it from a connected machine.

> Do you support JSON-RPC type of request like Ethereum does?

Not if the cardano-cli. It is an command line interface that works just like git would. You fetch the block on demand (otherwise you stay out of sync) and you update your local state locally.

> If we use cardano-cli as a black-box program to support ADA, how do we ensure that the value of “actual fee” is larger than that of “fee”? Because the fee and tx-bytes will only show after input and output being filled.

This is a common issue of the cardano transaction design. Because of the transaction being serialised in CBOR, it is not easy to predict what will be the size of the transaction (and therefor to deduct the fees).

> Can the private key of the address be exported using cardano-cli?

No. This feature is not implemented. If you want to add such feature, please the appropriate issue.

> Can we pull out the original transaction hash that has been signed (before being broadcasted) using cardano-cli?

No. This feature is not implemented. We could add this feature fairly easily. Please open an appropriate issue to ask for this feature to be added.

> Can the cardano-cli be used as a node, for the purpose of like searching for transactions and checking balances. Do you have an API for it?

Only for the transactions associated to a wallet you control. Have a look at `cardano-cli wallet *` commands

> How do other exchanges support ADA, is it via cardano-cli or cardano-sl?

They mostly utilise `cardano-sl` and the wallet backend written in haskell. You cannot do offline transaction signing with it though (seems like it is something you are looking for here).

> How do other exchanges confirm transactions? Is it by using lowest assurance, medium assurance or high assurance?

They wait for a certain amount of blocks being added to a transaction. Currently there is near 0 chances of fork, so transactions are very likely to be confirmed as soon as they reach one of the IOHK server. This will change when decentralisation will come.

**Comment by NicolasDP** [comment] 2019-03-26 09:35
You can find more help here too: https://cardanorust.iohkdev.io/cli-wallet

**Comment by NicolasDP** [comment] 2019-04-09 10:01
can we close this ticket if all questions have been answered ?

**Comment by BitrueExchange** [comment] 2019-04-09 13:21
Hey Nicolas, thank you for the great support. Yes we can close this ticket now.

**Closed as completed** 2019-04-09 17:57 UTC
